# Generated by Django 2.2.14 on 2024-08-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240809_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('type_space', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_repeated', models.IntegerField()),
                ('student_count', models.IntegerField()),
                ('academic_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.AcademicSpace')),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='type_document',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='user',
        ),
        migrations.RemoveField(
            model_name='repeticionesmaterias',
            name='academic_spaces',
        ),
        migrations.RemoveField(
            model_name='repeticionesmaterias',
            name='user',
        ),
        migrations.DeleteModel(
            name='EspaciosAcademicos',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='RepeticionesMaterias',
        ),
        migrations.DeleteModel(
            name='TypeDocument',
        ),
    ]
